# datapasta::tribble_paste()
# https://www.zipcodestogo.com/Maryland/
zip_county_table <- tibble::tribble(
  ~`ZIP_CODE`,                     ~City,          ~County,
     20601L,                 "Waldorf",        "Charles",
     20602L,                 "Waldorf",        "Charles",
     20603L,                 "Waldorf",        "Charles",
     20604L,                 "Waldorf",        "Charles",
     20606L,                   "Abell",    "Saint Mary's",
     20607L,                "Accokeek", "Prince George's",
     20608L,                 "Aquasco", "Prince George's",
     20609L,                  "Avenue",    "Saint Mary's",
     20610L,                 "Barstow",        "Calvert",
     20611L,               "Bel Alton",        "Charles",
     20612L,                "Benedict",        "Charles",
     20613L,              "Brandywine", "Prince George's",
     20615L,          "Broomes Island",        "Calvert",
     20616L,             "Bryans Road",        "Charles",
     20617L,               "Bryantown",        "Charles",
     20618L,                "Bushwood",    "Saint Mary's",
     20619L,              "California",    "Saint Mary's",
     20620L,                "Callaway",    "Saint Mary's",
     20621L,                "Chaptico",    "Saint Mary's",
     20622L,          "Charlotte Hall",    "Saint Mary's",
     20623L,              "Cheltenham", "Prince George's",
     20624L,                "Clements",    "Saint Mary's",
     20625L,             "Cobb Island",        "Charles",
     20626L,           "Coltons Point",    "Saint Mary's",
     20627L,                 "Compton",    "Saint Mary's",
     20628L,                 "Dameron",    "Saint Mary's",
     20629L,                  "Dowell",        "Calvert",
     20630L,                 "Drayden",    "Saint Mary's",
     20632L,                "Faulkner",        "Charles",
     20634L,             "Great Mills",    "Saint Mary's",
     20635L,                   "Helen",    "Saint Mary's",
     20636L,               "Hollywood",    "Saint Mary's",
     20637L,             "Hughesville",        "Charles",
     20639L,             "Huntingtown",        "Calvert",
     20640L,             "Indian Head",        "Charles",
     20643L,               "Ironsides",        "Charles",
     20645L,                   "Issue",        "Charles",
     20646L,                "La Plata",        "Charles",
     20650L,             "Leonardtown",    "Saint Mary's",
     20653L,          "Lexington Park",    "Saint Mary's",
     20656L,               "Loveville",    "Saint Mary's",
     20657L,                   "Lusby",        "Calvert",
     20658L,                 "Marbury",        "Charles",
     20659L,          "Mechanicsville",    "Saint Mary's",
     20660L,                "Morganza",    "Saint Mary's",
     20661L,          "Mount Victoria",        "Charles",
     20662L,                "Nanjemoy",        "Charles",
     20664L,                 "Newburg",        "Charles",
     20667L,               "Park Hall",    "Saint Mary's",
     20670L,          "Patuxent River",    "Saint Mary's",
     20674L,             "Piney Point",    "Saint Mary's",
     20675L,                 "Pomfret",        "Charles",
     20676L,           "Port Republic",        "Calvert",
     20677L,            "Port Tobacco",        "Charles",
     20678L,        "Prince Frederick",        "Calvert",
     20680L,                   "Ridge",    "Saint Mary's",
     20682L,              "Rock Point",        "Charles",
     20684L,           "Saint Inigoes",    "Saint Mary's",
     20685L,           "Saint Leonard",        "Calvert",
     20686L,        "Saint Mary's City",    "Saint Mary's",
     20687L,                "Scotland",    "Saint Mary's",
     20688L,                "Solomons",        "Calvert",
     20689L,              "Sunderland",        "Calvert",
     20690L,            "Tall Timbers",    "Saint Mary's",
     20692L,              "Valley Lee",    "Saint Mary's",
     20693L,                 "Welcome",        "Charles",
     20695L,            "White Plains",        "Charles",
     20697L,    "Southern Md Facility", "Prince George's",
     20701L,      "Annapolis Junction",         "Howard",
     20703L,                  "Lanham", "Prince George's",
     20704L,              "Beltsville", "Prince George's",
     20705L,              "Beltsville", "Prince George's",
     20706L,                  "Lanham", "Prince George's",
     20707L,                  "Laurel", "Prince George's",
     20708L,                  "Laurel", "Prince George's",
     20709L,                  "Laurel", "Prince George's",
     20710L,             "Bladensburg", "Prince George's",
     20711L,                 "Lothian",   "Anne Arundel",
     20712L,           "Mount Rainier", "Prince George's",
     20714L,             "North Beach",        "Calvert",
     20715L,                   "Bowie", "Prince George's",
     20716L,                   "Bowie", "Prince George's",
     20717L,                   "Bowie", "Prince George's",
     20718L,                   "Bowie", "Prince George's",
     20719L,                   "Bowie", "Prince George's",
     20720L,                   "Bowie", "Prince George's",
     20721L,                   "Bowie", "Prince George's",
     20722L,               "Brentwood", "Prince George's",
     20723L,                  "Laurel",         "Howard",
     20724L,                  "Laurel",   "Anne Arundel",
     20725L,                  "Laurel", "Prince George's",
     20726L,                  "Laurel", "Prince George's",
     20731L,         "Capitol Heights", "Prince George's",
     20732L,        "Chesapeake Beach",        "Calvert",
     20733L,               "Churchton",   "Anne Arundel",
     20735L,                 "Clinton", "Prince George's",
     20736L,                  "Owings",        "Calvert",
     20737L,               "Riverdale", "Prince George's",
     20738L,               "Riverdale", "Prince George's",
     20740L,            "College Park", "Prince George's",
     20741L,            "College Park", "Prince George's",
     20742L,            "College Park", "Prince George's",
     20743L,         "Capitol Heights", "Prince George's",
     20744L,         "Fort Washington", "Prince George's",
     20745L,               "Oxon Hill", "Prince George's",
     20746L,                "Suitland", "Prince George's",
     20747L,        "District Heights", "Prince George's",
     20748L,            "Temple Hills", "Prince George's",
     20749L,         "Fort Washington", "Prince George's",
     20750L,               "Oxon Hill", "Prince George's",
     20751L,                   "Deale",   "Anne Arundel",
     20752L,                "Suitland", "Prince George's",
     20753L,        "District Heights", "Prince George's",
     20754L,                 "Dunkirk",        "Calvert",
     20755L,     "Fort George G Meade",   "Anne Arundel",
     20757L,            "Temple Hills", "Prince George's",
     20758L,              "Friendship",   "Anne Arundel",
     20759L,                  "Fulton",         "Howard",
     20762L,  "Andrews Air Force Base", "Prince George's",
     20763L,                  "Savage",         "Howard",
     20764L,              "Shady Side",   "Anne Arundel",
     20765L,              "Galesville",   "Anne Arundel",
     20768L,               "Greenbelt", "Prince George's",
     20769L,              "Glenn Dale", "Prince George's",
     20770L,               "Greenbelt", "Prince George's",
     20771L,               "Greenbelt", "Prince George's",
     20772L,          "Upper Marlboro", "Prince George's",
     20773L,          "Upper Marlboro", "Prince George's",
     20774L,          "Upper Marlboro", "Prince George's",
     20775L,          "Upper Marlboro", "Prince George's",
     20776L,                 "Harwood",   "Anne Arundel",
     20777L,                "Highland",         "Howard",
     20778L,              "West River",   "Anne Arundel",
     20779L,          "Tracys Landing",   "Anne Arundel",
     20781L,             "Hyattsville", "Prince George's",
     20782L,             "Hyattsville", "Prince George's",
     20783L,             "Hyattsville", "Prince George's",
     20784L,             "Hyattsville", "Prince George's",
     20785L,             "Hyattsville", "Prince George's",
     20787L,             "Hyattsville", "Prince George's",
     20788L,             "Hyattsville", "Prince George's",
     20790L,         "Capitol Heights", "Prince George's",
     20791L,         "Capitol Heights", "Prince George's",
     20792L,          "Upper Marlboro", "Prince George's",
     20794L,                  "Jessup",         "Howard",
     20797L,    "Southern Md Facility", "Prince George's",
     20799L,         "Capitol Heights", "Prince George's",
     20810L,                "Bethesda",     "Montgomery",
     20811L,                "Bethesda",     "Montgomery",
     20812L,               "Glen Echo",     "Montgomery",
     20813L,                "Bethesda",     "Montgomery",
     20814L,                "Bethesda",     "Montgomery",
     20815L,             "Chevy Chase",     "Montgomery",
     20816L,                "Bethesda",     "Montgomery",
     20817L,                "Bethesda",     "Montgomery",
     20818L,              "Cabin John",     "Montgomery",
     20824L,                "Bethesda",     "Montgomery",
     20825L,             "Chevy Chase",     "Montgomery",
     20827L,                "Bethesda",     "Montgomery",
     20830L,                   "Olney",     "Montgomery",
     20832L,                   "Olney",     "Montgomery",
     20833L,             "Brookeville",     "Montgomery",
     20837L,             "Poolesville",     "Montgomery",
     20838L,             "Barnesville",     "Montgomery",
     20839L,             "Beallsville",     "Montgomery",
     20841L,                   "Boyds",     "Montgomery",
     20842L,               "Dickerson",     "Montgomery",
     20847L,               "Rockville",     "Montgomery",
     20848L,               "Rockville",     "Montgomery",
     20849L,               "Rockville",     "Montgomery",
     20850L,               "Rockville",     "Montgomery",
     20851L,               "Rockville",     "Montgomery",
     20852L,               "Rockville",     "Montgomery",
     20853L,               "Rockville",     "Montgomery",
     20854L,                 "Potomac",     "Montgomery",
     20855L,                 "Derwood",     "Montgomery",
     20857L,               "Rockville",     "Montgomery",
     20859L,                 "Potomac",     "Montgomery",
     20860L,            "Sandy Spring",     "Montgomery",
     20861L,                  "Ashton",     "Montgomery",
     20862L,                "Brinklow",     "Montgomery",
     20866L,            "Burtonsville",     "Montgomery",
     20868L,            "Spencerville",     "Montgomery",
     20871L,              "Clarksburg",     "Montgomery",
     20872L,                "Damascus",     "Montgomery",
     20874L,              "Germantown",     "Montgomery",
     20875L,              "Germantown",     "Montgomery",
     20876L,              "Germantown",     "Montgomery",
     20877L,            "Gaithersburg",     "Montgomery",
     20878L,            "Gaithersburg",     "Montgomery",
     20879L,            "Gaithersburg",     "Montgomery",
     20880L,        "Washington Grove",     "Montgomery",
     20882L,            "Gaithersburg",     "Montgomery",
     20883L,            "Gaithersburg",     "Montgomery",
     20884L,            "Gaithersburg",     "Montgomery",
     20885L,            "Gaithersburg",     "Montgomery",
     20886L,      "Montgomery Village",     "Montgomery",
     20889L,                "Bethesda",     "Montgomery",
     20891L,              "Kensington",     "Montgomery",
     20892L,                "Bethesda",     "Montgomery",
     20894L,                "Bethesda",     "Montgomery",
     20895L,              "Kensington",     "Montgomery",
     20896L,            "Garrett Park",     "Montgomery",
     20897L,     "Suburb Maryland Fac",     "Montgomery",
     20898L,            "Gaithersburg",     "Montgomery",
     20899L,            "Gaithersburg",     "Montgomery",
     20901L,           "Silver Spring",     "Montgomery",
     20902L,           "Silver Spring",     "Montgomery",
     20903L,           "Silver Spring",     "Montgomery",
     20904L,           "Silver Spring",     "Montgomery",
     20905L,           "Silver Spring",     "Montgomery",
     20906L,           "Silver Spring",     "Montgomery",
     20907L,           "Silver Spring",     "Montgomery",
     20908L,           "Silver Spring",     "Montgomery",
     20910L,           "Silver Spring",     "Montgomery",
     20911L,           "Silver Spring",     "Montgomery",
     20912L,             "Takoma Park",     "Montgomery",
     20913L,             "Takoma Park",     "Montgomery",
     20914L,           "Silver Spring",     "Montgomery",
     20915L,           "Silver Spring",     "Montgomery",
     20916L,           "Silver Spring",     "Montgomery",
     20918L,           "Silver Spring",     "Montgomery",
     20993L,           "Silver Spring",     "Montgomery",
     20997L,           "Silver Spring",     "Montgomery",
     21001L,                "Aberdeen",        "Harford",
     21005L, "Aberdeen Proving Ground",        "Harford",
     21009L,                "Abingdon",        "Harford",
     21010L,               "Gunpowder",        "Harford",
     21012L,                  "Arnold",   "Anne Arundel",
     21013L,                 "Baldwin",      "Baltimore",
     21014L,                 "Bel Air",        "Harford",
     21015L,                 "Bel Air",        "Harford",
     21017L,                 "Belcamp",        "Harford",
     21018L,                  "Benson",        "Harford",
     21020L,                  "Boring",      "Baltimore",
     21022L,          "Brooklandville",      "Baltimore",
     21023L,                  "Butler",      "Baltimore",
     21027L,                   "Chase",      "Baltimore",
     21028L,             "Churchville",        "Harford",
     21029L,             "Clarksville",         "Howard",
     21030L,            "Cockeysville",      "Baltimore",
     21031L,             "Hunt Valley",      "Baltimore",
     21032L,             "Crownsville",   "Anne Arundel",
     21034L,              "Darlington",        "Harford",
     21035L,           "Davidsonville",   "Anne Arundel",
     21036L,                  "Dayton",         "Howard",
     21037L,               "Edgewater",   "Anne Arundel",
     21040L,                "Edgewood",        "Harford",
     21041L,           "Ellicott City",         "Howard",
     21042L,           "Ellicott City",         "Howard",
     21043L,           "Ellicott City",         "Howard",
     21044L,                "Columbia",         "Howard",
     21045L,                "Columbia",         "Howard",
     21046L,                "Columbia",         "Howard",
     21047L,                "Fallston",        "Harford",
     21048L,               "Finksburg",        "Carroll",
     21050L,             "Forest Hill",        "Harford",
     21051L,                    "Fork",      "Baltimore",
     21052L,             "Fort Howard",      "Baltimore",
     21053L,                "Freeland",      "Baltimore",
     21054L,               "Gambrills",   "Anne Arundel",
     21056L,           "Gibson Island",   "Anne Arundel",
     21057L,                "Glen Arm",      "Baltimore",
     21060L,             "Glen Burnie",   "Anne Arundel",
     21061L,             "Glen Burnie",   "Anne Arundel",
     21062L,             "Glen Burnie",   "Anne Arundel",
     21065L,             "Hunt Valley",      "Baltimore",
     21071L,                 "Glyndon",      "Baltimore",
     21074L,               "Hampstead",        "Carroll",
     21075L,                "Elkridge",         "Howard",
     21076L,                 "Hanover",   "Anne Arundel",
     21077L,                 "Harmans",   "Anne Arundel",
     21078L,          "Havre De Grace",        "Harford",
     21082L,                   "Hydes",      "Baltimore",
     21084L,           "Jarrettsville",        "Harford",
     21085L,                   "Joppa",        "Harford",
     21087L,              "Kingsville",      "Baltimore",
     21088L,                "Lineboro",        "Carroll",
     21090L,       "Linthicum Heights",   "Anne Arundel",
     21092L,              "Long Green",      "Baltimore",
     21093L,    "Lutherville Timonium",      "Baltimore",
     21094L,    "Lutherville Timonium",      "Baltimore",
     21098L,                 "Hanover",   "Anne Arundel",
     21102L,              "Manchester",        "Carroll",
     21104L,          "Marriottsville",        "Carroll",
     21105L,           "Maryland Line",      "Baltimore",
     21106L,                    "Mayo",   "Anne Arundel",
     21108L,            "Millersville",   "Anne Arundel",
     21111L,                 "Monkton",      "Baltimore",
     21113L,                 "Odenton",   "Anne Arundel",
     21114L,                 "Crofton",   "Anne Arundel",
     21117L,            "Owings Mills",      "Baltimore",
     21120L,                 "Parkton",      "Baltimore",
     21122L,                "Pasadena",   "Anne Arundel",
     21123L,                "Pasadena",   "Anne Arundel",
     21128L,              "Perry Hall",      "Baltimore",
     21130L,                "Perryman",        "Harford",
     21131L,                 "Phoenix",      "Baltimore",
     21132L,              "Pylesville",        "Harford",
     21133L,            "Randallstown",      "Baltimore",
     21136L,            "Reisterstown",      "Baltimore",
     21139L,               "Riderwood",      "Baltimore",
     21140L,                    "Riva",   "Anne Arundel",
     21144L,                  "Severn",   "Anne Arundel",
     21146L,            "Severna Park",   "Anne Arundel",
     21150L,            "Simpsonville",         "Howard",
     21152L,          "Sparks Glencoe",      "Baltimore",
     21153L,               "Stevenson",      "Baltimore",
     21154L,                  "Street",        "Harford",
     21155L,                 "Upperco",      "Baltimore",
     21156L,             "Upper Falls",      "Baltimore",
     21157L,             "Westminster",        "Carroll",
     21158L,             "Westminster",        "Carroll",
     21160L,               "Whiteford",        "Harford",
     21161L,              "White Hall",        "Harford",
     21162L,             "White Marsh",      "Baltimore",
     21163L,               "Woodstock",         "Howard",
     21201L,               "Baltimore", "Baltimore City",
     21202L,               "Baltimore", "Baltimore City",
     21203L,               "Baltimore", "Baltimore City",
     21204L,                  "Towson",      "Baltimore",
     21205L,               "Baltimore", "Baltimore City",
     21206L,               "Baltimore", "Baltimore City",
     21207L,               "Gwynn Oak",      "Baltimore",
     21208L,              "Pikesville",      "Baltimore",
     21209L,               "Baltimore", "Baltimore City",
     21210L,               "Baltimore", "Baltimore City",
     21211L,               "Baltimore", "Baltimore City",
     21212L,               "Baltimore", "Baltimore City",
     21213L,               "Baltimore", "Baltimore City",
     21214L,               "Baltimore", "Baltimore City",
     21215L,               "Baltimore", "Baltimore City",
     21216L,               "Baltimore", "Baltimore City",
     21217L,               "Baltimore", "Baltimore City",
     21218L,               "Baltimore", "Baltimore City",
     21219L,          "Sparrows Point",      "Baltimore",
     21220L,            "Middle River",      "Baltimore",
     21221L,                   "Essex",      "Baltimore",
     21222L,                 "Dundalk",      "Baltimore",
     21223L,               "Baltimore", "Baltimore City",
     21224L,               "Baltimore", "Baltimore City",
     21225L,                "Brooklyn", "Baltimore City",
     21226L,              "Curtis Bay",   "Anne Arundel",
     21227L,              "Halethorpe",      "Baltimore",
     21228L,             "Catonsville",      "Baltimore",
     21229L,               "Baltimore", "Baltimore City",
     21230L,               "Baltimore", "Baltimore City",
     21231L,               "Baltimore", "Baltimore City",
     21233L,               "Baltimore", "Baltimore City",
     21234L,               "Parkville",      "Baltimore",
     21235L,               "Baltimore", "Baltimore City",
     21236L,              "Nottingham",      "Baltimore",
     21237L,                "Rosedale",      "Baltimore",
     21239L,               "Baltimore", "Baltimore City",
     21240L,               "Baltimore",   "Anne Arundel",
     21241L,               "Baltimore", "Baltimore City",
     21244L,            "Windsor Mill",      "Baltimore",
     21250L,               "Baltimore",      "Baltimore",
     21251L,               "Baltimore", "Baltimore City",
     21252L,               "Baltimore",      "Baltimore",
     21263L,               "Baltimore", "Baltimore City",
     21264L,               "Baltimore", "Baltimore City",
     21265L,               "Baltimore", "Baltimore City",
     21268L,               "Baltimore", "Baltimore City",
     21270L,               "Baltimore", "Baltimore City",
     21273L,               "Baltimore", "Baltimore City",
     21274L,               "Baltimore", "Baltimore City",
     21275L,               "Baltimore", "Baltimore City",
     21278L,               "Baltimore", "Baltimore City",
     21279L,               "Baltimore", "Baltimore City",
     21280L,               "Baltimore", "Baltimore City",
     21281L,               "Baltimore", "Baltimore City",
     21282L,               "Baltimore",      "Baltimore",
     21283L,               "Baltimore", "Baltimore City",
     21284L,               "Baltimore",      "Baltimore",
     21285L,               "Baltimore",      "Baltimore",
     21286L,                  "Towson",      "Baltimore",
     21287L,               "Baltimore", "Baltimore City",
     21288L,               "Baltimore", "Baltimore City",
     21289L,               "Baltimore", "Baltimore City",
     21290L,               "Baltimore", "Baltimore City",
     21297L,               "Baltimore", "Baltimore City",
     21298L,               "Baltimore", "Baltimore City",
     21401L,               "Annapolis",   "Anne Arundel",
     21402L,               "Annapolis",   "Anne Arundel",
     21403L,               "Annapolis",   "Anne Arundel",
     21404L,               "Annapolis",   "Anne Arundel",
     21405L,               "Annapolis",   "Anne Arundel",
     21409L,               "Annapolis",   "Anne Arundel",
     21411L,               "Annapolis",   "Anne Arundel",
     21412L,               "Annapolis",   "Anne Arundel",
     21501L,              "Cumberland",       "Allegany",
     21502L,              "Cumberland",       "Allegany",
     21503L,              "Cumberland",       "Allegany",
     21504L,              "Cumberland",       "Allegany",
     21505L,              "Cumberland",       "Allegany",
     21520L,                "Accident",        "Garrett",
     21521L,                  "Barton",       "Allegany",
     21522L,               "Bittinger",        "Garrett",
     21523L,             "Bloomington",        "Garrett",
     21524L,           "Corriganville",       "Allegany",
     21528L,           "Eckhart Mines",       "Allegany",
     21529L,               "Ellerslie",       "Allegany",
     21530L,              "Flintstone",       "Allegany",
     21531L,            "Friendsville",        "Garrett",
     21532L,               "Frostburg",       "Allegany",
     21536L,             "Grantsville",        "Garrett",
     21538L,              "Kitzmiller",        "Garrett",
     21539L,              "Lonaconing",       "Allegany",
     21540L,                    "Luke",       "Allegany",
     21541L,                "Mc Henry",        "Garrett",
     21542L,                 "Midland",       "Allegany",
     21543L,              "Midlothian",       "Allegany",
     21545L,            "Mount Savage",       "Allegany",
     21550L,                 "Oakland",        "Garrett",
     21555L,                 "Oldtown",       "Allegany",
     21556L,                   "Pinto",       "Allegany",
     21557L,                "Rawlings",       "Allegany",
     21560L,              "Spring Gap",       "Allegany",
     21561L,                 "Swanton",        "Garrett",
     21562L,             "Westernport",       "Allegany",
     21601L,                  "Easton",         "Talbot",
     21606L,                  "Easton",         "Talbot",
     21607L,                 "Barclay",    "Queen Anne's",
     21609L,               "Bethlehem",       "Caroline",
     21610L,               "Betterton",           "Kent",
     21612L,                  "Bozman",         "Talbot",
     21613L,               "Cambridge",     "Dorchester",
     21617L,             "Centreville",    "Queen Anne's",
     21619L,                 "Chester",    "Queen Anne's",
     21620L,             "Chestertown",           "Kent",
     21622L,            "Church Creek",     "Dorchester",
     21623L,             "Church Hill",    "Queen Anne's",
     21624L,               "Claiborne",         "Talbot",
     21625L,                 "Cordova",         "Talbot",
     21626L,                   "Crapo",     "Dorchester",
     21627L,               "Crocheron",     "Dorchester",
     21628L,                "Crumpton",    "Queen Anne's",
     21629L,                  "Denton",       "Caroline",
     21631L,         "East New Market",     "Dorchester",
     21632L,            "Federalsburg",       "Caroline",
     21634L,           "Fishing Creek",     "Dorchester",
     21635L,                  "Galena",           "Kent",
     21636L,               "Goldsboro",       "Caroline",
     21638L,             "Grasonville",    "Queen Anne's",
     21639L,              "Greensboro",       "Caroline",
     21640L,               "Henderson",       "Caroline",
     21641L,               "Hillsboro",       "Caroline",
     21643L,                 "Hurlock",     "Dorchester",
     21644L,               "Ingleside",    "Queen Anne's",
     21645L,            "Kennedyville",           "Kent",
     21647L,                "Mcdaniel",         "Talbot",
     21648L,                 "Madison",     "Dorchester",
     21649L,                 "Marydel",       "Caroline",
     21650L,                  "Massey",           "Kent",
     21651L,              "Millington",           "Kent",
     21652L,                 "Neavitt",         "Talbot",
     21653L,                 "Newcomb",         "Talbot",
     21654L,                  "Oxford",         "Talbot",
     21655L,                 "Preston",       "Caroline",
     21656L,                   "Price",    "Queen Anne's",
     21657L,              "Queen Anne",    "Queen Anne's",
     21658L,              "Queenstown",    "Queen Anne's",
     21659L,              "Rhodesdale",     "Dorchester",
     21660L,                 "Ridgely",       "Caroline",
     21661L,               "Rock Hall",           "Kent",
     21662L,               "Royal Oak",         "Talbot",
     21663L,          "Saint Michaels",         "Talbot",
     21664L,               "Secretary",     "Dorchester",
     21665L,                "Sherwood",         "Talbot",
     21666L,            "Stevensville",    "Queen Anne's",
     21667L,              "Still Pond",           "Kent",
     21668L,            "Sudlersville",    "Queen Anne's",
     21669L,          "Taylors Island",     "Dorchester",
     21670L,             "Templeville",       "Caroline",
     21671L,                "Tilghman",         "Talbot",
     21672L,               "Toddville",     "Dorchester",
     21673L,                  "Trappe",         "Talbot",
     21675L,                 "Wingate",     "Dorchester",
     21676L,                 "Wittman",         "Talbot",
     21677L,                "Woolford",     "Dorchester",
     21678L,                  "Worton",           "Kent",
     21679L,               "Wye Mills",         "Talbot",
     21681L,                 "Ridgely",       "Caroline",
     21682L,                 "Ridgely",       "Caroline",
     21683L,                 "Ridgely",       "Caroline",
     21684L,                 "Ridgely",       "Caroline",
     21685L,                 "Ridgely",       "Caroline",
     21686L,                 "Ridgely",       "Caroline",
     21687L,                 "Ridgely",       "Caroline",
     21688L,                 "Ridgely",       "Caroline",
     21690L,             "Chestertown",    "Queen Anne's",
     21701L,               "Frederick",      "Frederick",
     21702L,               "Frederick",      "Frederick",
     21703L,               "Frederick",      "Frederick",
     21704L,               "Frederick",      "Frederick",
     21705L,               "Frederick",      "Frederick",
     21709L,               "Frederick",      "Frederick",
     21710L,               "Adamstown",      "Frederick",
     21711L,                "Big Pool",     "Washington",
     21713L,               "Boonsboro",     "Washington",
     21714L,        "Braddock Heights",      "Frederick",
     21715L,             "Brownsville",     "Washington",
     21716L,               "Brunswick",      "Frederick",
     21717L,             "Buckeystown",      "Frederick",
     21718L,           "Burkittsville",      "Frederick",
     21719L,                 "Cascade",     "Washington",
     21720L,                "Cavetown",     "Washington",
     21721L,              "Chewsville",     "Washington",
     21722L,            "Clear Spring",     "Washington",
     21723L,              "Cooksville",         "Howard",
     21727L,              "Emmitsburg",      "Frederick",
     21733L,                "Fairplay",     "Washington",
     21734L,               "Funkstown",     "Washington",
     21737L,                 "Glenelg",         "Howard",
     21738L,                "Glenwood",         "Howard",
     21740L,              "Hagerstown",     "Washington",
     21741L,              "Hagerstown",     "Washington",
     21742L,              "Hagerstown",     "Washington",
     21746L,              "Hagerstown",     "Washington",
     21747L,              "Hagerstown",     "Washington",
     21748L,              "Hagerstown",     "Washington",
     21749L,              "Hagerstown",     "Washington",
     21750L,                 "Hancock",     "Washington",
     21754L,              "Ijamsville",      "Frederick",
     21755L,               "Jefferson",      "Frederick",
     21756L,             "Keedysville",     "Washington",
     21757L,                  "Keymar",        "Carroll",
     21758L,               "Knoxville",      "Frederick",
     21759L,              "Ladiesburg",      "Frederick",
     21762L,             "Libertytown",      "Frederick",
     21765L,                  "Lisbon",         "Howard",
     21766L,          "Little Orleans",       "Allegany",
     21767L,            "Maugansville",     "Washington",
     21769L,              "Middletown",      "Frederick",
     21770L,                "Monrovia",      "Frederick",
     21771L,              "Mount Airy",      "Frederick",
     21773L,              "Myersville",      "Frederick",
     21774L,              "New Market",      "Frederick",
     21775L,              "New Midway",      "Frederick",
     21776L,             "New Windsor",        "Carroll",
     21777L,          "Point Of Rocks",      "Frederick",
     21778L,             "Rocky Ridge",      "Frederick",
     21779L,            "Rohrersville",     "Washington",
     21780L,           "Sabillasville",      "Frederick",
     21781L,             "Saint James",     "Washington",
     21782L,              "Sharpsburg",     "Washington",
     21783L,              "Smithsburg",     "Washington",
     21784L,              "Sykesville",        "Carroll",
     21787L,               "Taneytown",        "Carroll",
     21788L,                "Thurmont",      "Frederick",
     21790L,               "Tuscarora",      "Frederick",
     21791L,            "Union Bridge",        "Carroll",
     21792L,              "Unionville",      "Frederick",
     21793L,            "Walkersville",      "Frederick",
     21794L,         "West Friendship",         "Howard",
     21795L,            "Williamsport",     "Washington",
     21797L,                "Woodbine",         "Howard",
     21798L,               "Woodsboro",      "Frederick",
     21801L,               "Salisbury",       "Wicomico",
     21802L,               "Salisbury",       "Wicomico",
     21803L,               "Salisbury",       "Wicomico",
     21804L,               "Salisbury",       "Wicomico",
     21810L,                   "Allen",       "Wicomico",
     21811L,                  "Berlin",      "Worcester",
     21813L,             "Bishopville",      "Worcester",
     21814L,                 "Bivalve",       "Wicomico",
     21817L,               "Crisfield",       "Somerset",
     21821L,             "Deal Island",       "Somerset",
     21822L,                    "Eden",      "Worcester",
     21824L,                   "Ewell",       "Somerset",
     21826L,               "Fruitland",       "Wicomico",
     21829L,              "Girdletree",      "Worcester",
     21830L,                  "Hebron",       "Wicomico",
     21835L,                "Linkwood",     "Dorchester",
     21836L,                 "Manokin",       "Somerset",
     21837L,         "Mardela Springs",       "Wicomico",
     21838L,          "Marion Station",       "Somerset",
     21840L,               "Nanticoke",       "Wicomico",
     21841L,                  "Newark",      "Worcester",
     21842L,              "Ocean City",      "Worcester",
     21843L,              "Ocean City",      "Worcester",
     21849L,             "Parsonsburg",       "Wicomico",
     21850L,              "Pittsville",       "Wicomico",
     21851L,           "Pocomoke City",      "Worcester",
     21852L,             "Powellville",       "Wicomico",
     21853L,           "Princess Anne",       "Somerset",
     21856L,                "Quantico",       "Wicomico",
     21857L,                "Rehobeth",       "Somerset",
     21861L,               "Sharptown",       "Wicomico",
     21862L,                 "Showell",      "Worcester",
     21863L,               "Snow Hill",      "Worcester",
     21864L,                "Stockton",      "Worcester",
     21865L,                 "Tyaskin",       "Wicomico",
     21866L,                "Tylerton",       "Somerset",
     21867L,         "Upper Fairmount",       "Somerset",
     21869L,                  "Vienna",     "Dorchester",
     21871L,                "Westover",       "Somerset",
     21872L,             "Whaleyville",      "Worcester",
     21874L,                "Willards",       "Wicomico",
     21875L,                  "Delmar",       "Wicomico",
     21890L,                "Westover",       "Somerset",
     21901L,              "North East",          "Cecil",
     21902L,             "Perry Point",          "Cecil",
     21903L,              "Perryville",          "Cecil",
     21904L,            "Port Deposit",          "Cecil",
     21911L,              "Rising Sun",          "Cecil",
     21912L,                 "Warwick",          "Cecil",
     21913L,                "Cecilton",          "Cecil",
     21914L,             "Charlestown",          "Cecil",
     21915L,         "Chesapeake City",          "Cecil",
     21916L,                  "Childs",          "Cecil",
     21917L,                  "Colora",          "Cecil",
     21918L,               "Conowingo",          "Cecil",
     21919L,              "Earleville",          "Cecil",
     21920L,               "Elk Mills",          "Cecil",
     21921L,                  "Elkton",          "Cecil",
     21922L,                  "Elkton",          "Cecil",
     21930L,              "Georgetown",          "Cecil"
  )
save(zip_county_table, file = 'www/zip_county_table.Rdata')
